### ISSUE TITLE
Anyway to finish the floatingView?

### ISSUE THREAD

**Issue by mosamabinomar** [recruit-lifestyle/FloatingView#54]
Calling ` floatingViewManager.removeAllViewToWindow();` cause <b>IllegalArgumentException.</b>
java.lang.IllegalArgumentException: View=jp.co.recruit_lifestyle.android.floatingview.FloatingView{f72bf3a V.E...... ......I. 0,0-540,303} not attached to window manager
                                                       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)
                                                       at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:368)
                                                       at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:99)
                                                       at jp.co.recruit_lifestyle.android.floatingview.FloatingView$FloatingAnimationHandler.handleMessage(FloatingView.java:1051)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by YoshihideSogawa** [comment]
Does the same error occur even if 2.2.2-beta1 is used?
https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.2.2-beta1

**Comment by mosamabinomar** [comment]
no. I think fixed. Thanks
