### ISSUE TITLE
Android O - Crash because of permission handling

### ISSUE THREAD

**Issue by luserdroid** [recruit-lifestyle/FloatingView#59]
07-26 22:53:21.622 4970-4970/jp.co.recruit.floatingview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: jp.co.recruit.floatingview, PID: 4970
                                                                          java.lang.RuntimeException: Unable to start service jp.co.recruit_lifestyle.sample.service.ChatHeadService@e7250e9 with Intent { cmp=jp.co.recruit.floatingview/jp.co.recruit_lifestyle.sample.service.ChatHeadService }: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@fe840cc -- permission denied for window type 2007
                                                                              at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)
                                                                              at android.app.ActivityThread.-wrap20(Unknown Source:0)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                           Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@fe840cc -- permission denied for window type 2007
                                                                              at android.view.ViewRootImpl.setView(ViewRootImpl.java:788)
                                                                              at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                                                                              at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
                                                                              at jp.co.recruit_lifestyle.android.floatingview.FloatingViewManager.addViewToWindow(FloatingViewManager.java:493)
                                                                              at jp.co.recruit_lifestyle.sample.service.ChatHeadService.onStartCommand(ChatHeadService.java:68)
                                                                              at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
                                                                              at android.app.ActivityThread.-wrap20(Unknown Source:0) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                              at android.os.Looper.loop(Looper.java:164) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6540) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by YoshihideSogawa** [comment]
Support for Android O is testing now.
Use [2.2.3-beta1](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.2.3-beta1).

**Comment by luserdroid** [comment]
Can you recommend it also for production use ?

**Comment by aimanzakikagzi** [comment]
I am facing same issue, its crashing.

**Comment by YoshihideSogawa** [comment]
Use [Ver 2.2.3](https://github.com/recruit-lifestyle/FloatingView/releases/tag/2.2.3)
