### ISSUE TITLE
Crash for the sample project

### ISSUE THREAD

**Issue by DonLiangGit** [recruit-lifestyle/FloatingView#6]
```
java.lang.NoSuchMethodError: No static method canDrawOverlays(Landroid/content/Context;)Z in class Landroid/provider/Settings; or its super classes (declaration of 'android.provider.Settings' appears in /system/framework/framework.jar:classes2.dex)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at jp.co.recruit_lifestyle.sample.fragment.FloatingViewControlFragment.showChatHead(FloatingViewControlFragment.java:165)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at jp.co.recruit_lifestyle.sample.fragment.FloatingViewControlFragment.access$100(FloatingViewControlFragment.java:26)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at jp.co.recruit_lifestyle.sample.fragment.FloatingViewControlFragment$2.onClick(FloatingViewControlFragment.java:98)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at android.view.View.performClick(View.java:4780)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:19866)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-03 16:50:16.142 26338-26338/jp.co.recruit.floatingview E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by DonLiangGit** [comment]
reference:
http://stackoverflow.com/questions/32061934/permission-from-manifest-doesnt-work-in-android-6

anyway, without the check will solve the problem :)

**Comment by DonLiangGit** [comment]
by the way, the toast can be spammed please check if the `toast` is empty and cancel it before try to make a new one. good work!

**Comment by YoshihideSogawa** [comment]
Thank you. Fixed error.

Toast is not necessary.And I have replaced the Toast to Log.
